# EXAMPLE ONLY
# Simple nginx router to show how you can access wallet endpoints from a specific
# API domain (instead of specifying the port #)
# Alertnatively you can access wallet with lcoin.yourdomain.org:8334 (mainnet)
# Without using this configuration

version: '2'
services:
  lcoin-wallet:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: bwallet.yourdomain.org
    volumes:
      - ./wallet-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - 80
    networks:
      - "lcoin"
      - "nginx-proxy"

networks:
  lcoin:
    external:
      name: "lcoin"
  nginx-proxy:
    external:
      name: "nginx-proxy"
