version: '2'

services:
  lcoin:
    image: purse/lcoin
    container_name: lcoin
    restart: unless-stopped
    ports:
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC/HTTP
      - "8334:8334" # Wallet
      #-- Testnet
      #- "18333:18333"
      #- "18332:18332" # RPC/HTTP
      #- "18334:18334"
    environment:
      LCOIN_CONFIG: /data/lcoin.conf
      VIRTUAL_HOST: lcoin.yourdomain.org
      VIRTUAL_PORT: 8332
      #VIRTUAL_PORT: 18332 # Testnest
    networks:
      - "lcoin"
      - "nginx-proxy"
    volumes:
      - ~/.lcoin:/data
      - ${PWD}/secrets/lcoin.conf:/data/lcoin.conf
      - ${PWD}/secrets/wallet.conf:/data/wallet.conf

  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx-proxy"
    volumes:
      - ./secrets/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  lcoin:
    external:
      name: "lcoin"
  nginx-proxy:
    external:
      name: "nginx-proxy"
